#! /bin/sh
set -e

ARCH="$(uname -m)"

SDRPLAY="OFF"
if [ "$ARCH" = x86_64 -o "$ARCH" = aarch64 ]; then
    SDRPLAY="ON"
fi

mkdir "$2"
cd "$2"
cmake "$1" -DOPT_BUILD_BLADERF_SOURCE=ON -DOPT_BUILD_LIMESDR_SOURCE=ON -DOPT_BUILD_SDRPLAY_SOURCE=$SDRPLAY -DOPT_BUILD_NEW_PORTAUDIO_SINK=ON -DOPT_BUILD_M17_DECODER=ON -DOPT_BUILD_PERSEUS_SOURCE=ON -DOPT_BUILD_RFNM_SOURCE=ON -DOPT_BUILD_FOBOSSDR_SOURCE=ON
